# Generated by Django 4.2.5 on 2023-09-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
