# Generated by Django 4.2.5 on 2023-09-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_online', '0003_product_image'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='Tienda_online.product'),
        ),
    ]
